sudo: true
dist: trusty 
language: c

before_install:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install swig

install: 
  - cd ..
  - git clone https://github.com/mozilla/sphinxbase
  - cd sphinxbase
  - ./autogen.sh
  - ./configure && make && sudo make install
  - cd ../pocketsphinx-1
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd swig
  - make 
  - cd java
  - make
